### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by tingkai-zhang** [rixwew/pytorch-fm#10]
Hi,
It threw out this error ``RuntimeError: CUDA error: device-side assert triggered``
 when running ``ffm`` model, can you please take a look at it and fix it? Thank you!

**Comment by rixwew** [comment]
I could not reproduce `RuntimeError: CUDA error: device-side assert triggered`
@tingkai-zhang Could you tell me your pytorch version and dataset name?

**Comment by tingkai-zhang** [comment]
> I could not reproduce `RuntimeError: CUDA error: device-side assert triggered`
> @tingkai-zhang Could you tell me your pytorch version and dataset name?

Thanks for replying. Been busy these days.

Pytorch Version：1.2
Dataset: MovieLens1M

Let me know if there is anything I could provide.

**Comment by rixwew** [comment]
Thank you for your time!
MovieLens1M error was reported in #6, and fixed with https://github.com/rixwew/pytorch-fm/commit/782d9598a25c37b77bbeb39ad28406087f2e5e01
If you are using pypi torchfm, please update the package.
```
pip install torchfm --upgrade
```

**Comment by tingkai-zhang** [comment]
Sweet. Thank you
