### ISSUE TITLE
How to get top 10 predicted items after training

### ISSUE THREAD

**Issue by tejasmhos** [rixwew/pytorch-fm#14]
After you train an instance of a model using PyTorch, how do you use that model to get the top 10 rated items, i.e., how do you get a model prediction.

**Comment by tejasmhos** [comment]
This is with regards to the neural collaborative filtering model, but I'm guessing it applies to all other models too.

**Comment by rixwew** [comment]
Typically, the topk search is done by simpler models like logistic regression or neighborhood search, and then re-ranked by deep learning models.

Here's a good reference.
https://arxiv.org/pdf/1606.07792.pdf
