### ISSUE TITLE
One mistake in class MultiLayerPerceptron(torch.nn.Module) in layers.py

### ISSUE THREAD

**Issue by BrandonCXY** [rixwew/pytorch-fm#24]
你好，你对于Class MultiLayerPerceptron里的forward function中的x的注释错误
原注释：:param x: Float tensor of size ``(batch_size, num_fields, embed_dim)``
应改为： :param x: Float tensor of size ``(batch_size, embed_dim)``

**Comment by rixwew** [comment]
Thank you! I fixed it.
