### ISSUE TITLE
FeatureEmbedding Implementation

### ISSUE THREAD

**Issue by tingkai-zhang** [rixwew/pytorch-fm#4]
Hi, congrats on your great work!
I was wondering why you add a offset before embedding?

https://github.com/rixwew/pytorch-fm/blob/a4cfa99aa23147b15a0df065553567dba859246d/torchfm/layer.py#L27

As I am looking at the implementation of xDeepFM, I didn't find the corresponding code in original tensorflow implementation.

**Comment by Drone-Banks** [comment]
The feature value of different filed all start from 1, but they are all embeded into the same matrix, so the offsets is needed.

**Comment by tingkai-zhang** [comment]
> The feature value of different filed all start from 1, but they are all embeded into the same matrix, so the offsets is needed.

Oh yeah. Thanks for replying!

**Comment by MogicianXD** [comment]
However, speed can be slower. Adding offset in preprocessing may be a better choice?
