### ISSUE TITLE
ValueError: Target and input must have the same number of elements. 

### ISSUE THREAD

**Issue by tingkai-zhang** [rixwew/pytorch-fm#9]
Hi, 
When ``nfm`` is used as model, the return value ``(batch_size, batch_size)`` does not have the right shape. 
This will cause a error when calculating the loss.

**Comment by rixwew** [comment]
I reproduced same error and released a quick fix patch. 
https://github.com/rixwew/pytorch-fm/commit/b75ea00637957d0881fa0db49068b02ca720b0f6
Thank you. @tingkai-zhang

**Comment by Drone-Banks** [comment]
@rixwew  same problem in  FNFM model

**Comment by rixwew** [comment]
@tingkai-zhang thank you for a bug report!
I fixed in https://github.com/rixwew/pytorch-fm/commit/dd5aa6d5743b59224d457e77e85154da33ee2a5a, and updated pypi package.

**Comment by tingkai-zhang** [comment]
Thanks!
